"""Add geographic coordinates to bookings table for RF-BONUS-003

Revision ID: 9af02f6938fd
Revises: ece03eef82d8
Create Date: 2025-11-13 16:19:40.567481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af02f6938fd'
down_revision: Union[str, Sequence[str], None] = 'ece03eef82d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('pickup_lat', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('pickup_lng', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('dropoff_lat', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('dropoff_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'dropoff_lng')
    op.drop_column('bookings', 'dropoff_lat')
    op.drop_column('bookings', 'pickup_lng')
    op.drop_column('bookings', 'pickup_lat')
    # ### end Alembic commands ###
