"""Add chat_messages table for RF-BONUS-004

Revision ID: 5e2798f5a46d
Revises: 9af02f6938fd
Create Date: 2025-11-13 16:42:21.668433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2798f5a46d'
down_revision: Union[str, Sequence[str], None] = '9af02f6938fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
