"""create_travel_requests_table

Revision ID: f53958ea175b
Revises: b38244ac70d6
Create Date: 2025-11-13 13:42:42.338767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53958ea175b'
down_revision: Union[str, Sequence[str], None] = 'b38244ac70d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lng', sa.Float(), nullable=False),
    sa.Column('destination_lat', sa.Float(), nullable=False),
    sa.Column('destination_lng', sa.Float(), nullable=False),
    sa.Column('origin_address', sa.String(length=200), nullable=True),
    sa.Column('destination_address', sa.String(length=200), nullable=True),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('time_from', sa.Time(), nullable=True),
    sa.Column('time_to', sa.Time(), nullable=True),
    sa.Column('seats_requested', sa.Integer(), nullable=False),
    sa.Column('passenger_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('matched_trip_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['matched_trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_requests_passenger_id'), 'travel_requests', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_travel_requests_status'), 'travel_requests', ['status'], unique=False)
    op.create_index(op.f('ix_travel_requests_travel_date'), 'travel_requests', ['travel_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travel_requests_travel_date'), table_name='travel_requests')
    op.drop_index(op.f('ix_travel_requests_status'), table_name='travel_requests')
    op.drop_index(op.f('ix_travel_requests_passenger_id'), table_name='travel_requests')
    op.drop_table('travel_requests')
    # ### end Alembic commands ###
