"""Add CO2 tracking fields to trips table

Revision ID: ece03eef82d8
Revises: f53958ea175b
Create Date: 2025-11-13 15:57:33.625648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece03eef82d8'
down_revision: Union[str, Sequence[str], None] = 'f53958ea175b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('vehicle_type', sa.String(length=20), nullable=False, server_default='gasoline'))
    op.add_column('trips', sa.Column('distance_km', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('co2_saved_per_passenger_kg', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('total_co2_saved_kg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'total_co2_saved_kg')
    op.drop_column('trips', 'co2_saved_per_passenger_kg')
    op.drop_column('trips', 'distance_km')
    op.drop_column('trips', 'vehicle_type')
    # ### end Alembic commands ###
